"""Uniform browser hardening headers for every HTTP response."""

import secrets
from collections.abc import Mapping

from starlette.datastructures import MutableHeaders
from starlette.types import ASGIApp, Message, Receive, Scope, Send

# Substituted with a fresh per-request nonce by SecurityHeadersMiddleware. The
# same nonce lands in scope["state"]["csp_nonce"] so the server-rendered HTML
# shells (/ , /login, /setup) can stamp it onto their single inline <script>.
CSP_NONCE_PLACEHOLDER = "__CSP_NONCE__"

DEFAULT_SECURITY_HEADERS: Mapping[str, str] = {
    # script-src carries a per-response nonce instead of 'unsafe-inline':
    # injected markup can no longer execute script. style-src intentionally
    # KEEPS 'unsafe-inline': a nonce on style-src would make browsers ignore
    # 'unsafe-inline' for that directive and thereby ban every style=""
    # ATTRIBUTE (nonces only whitelist <style> ELEMENTS). The 250KB dashboard
    # is regenerated by a separate build (tools/build_dashboard.py) and its
    # JS-rendered DOM must stay free to use style attributes without a silent
    # styling outage; style injection is not a script-execution vector.
    "Content-Security-Policy": (
        "default-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; "
        "object-src 'none'; img-src 'self' data:; font-src 'self'; "
        "style-src 'self' 'unsafe-inline'; "
        f"script-src 'self' 'nonce-{CSP_NONCE_PLACEHOLDER}'; "
        "connect-src 'self'; worker-src 'self'; manifest-src 'self'"
    ),
    "Cross-Origin-Opener-Policy": "same-origin",
    "Cross-Origin-Resource-Policy": "same-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=(), payment=()",
    "Referrer-Policy": "no-referrer",
    # includeSubDomains: the only public host is the apex (cactusbets.cloud),
    # served exclusively over Traefik TLS — no plaintext subdomain exists.
    # 'preload' is deliberately absent: preload-list inclusion is one-way and
    # was not operator-confirmed.
    "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "X-Robots-Tag": "noindex, nofollow, noarchive",
}

_PRIVATE_NO_STORE = "private, no-store"


class SecurityHeadersMiddleware:
    """Small ASGI middleware; avoids BaseHTTPMiddleware cancellation semantics."""

    def __init__(
        self,
        app: ASGIApp,
        headers: Mapping[str, str] = DEFAULT_SECURITY_HEADERS,
    ) -> None:
        self._app = app
        self._headers = tuple(headers.items())

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self._app(scope, receive, send)
            return

        # Fresh CSP nonce per request, exposed to handlers via request.state
        # BEFORE the app runs so HTML shells can stamp it on inline <script>.
        nonce = secrets.token_urlsafe(16)
        scope.setdefault("state", {})["csp_nonce"] = nonce

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = MutableHeaders(scope=message)
                for name, value in self._headers:
                    # This is an application invariant, not a route default: a
                    # handler must not accidentally weaken the global policy.
                    if CSP_NONCE_PLACEHOLDER in value:
                        value = value.replace(CSP_NONCE_PLACEHOLDER, nonce)
                    headers[name] = value
                # Authenticated picks/performance/bankroll responses must never
                # enter browser or intermediary caches. Preserve an explicit
                # revalidation policy (the public manifest/service worker use
                # ``no-cache``), but make absent or route-level bare ``no-store``
                # policies private and legacy-proxy compatible.
                cache_control = headers.get("Cache-Control")
                if cache_control is None or cache_control.strip().casefold() == "no-store":
                    headers["Cache-Control"] = _PRIVATE_NO_STORE
                    headers["Pragma"] = "no-cache"
            await send(message)

        await self._app(scope, receive, send_with_headers)
