"""initial 14-table warehouse

Revision ID: bc9e18be0148
Revises: 
Create Date: 2026-06-10 13:15:26.173089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc9e18be0148'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankroll_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', name='uq_bankroll_snapshots_date')
    )
    op.create_table('sports',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('leagues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sport_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'key', name='uq_leagues_sport_key')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('sport_id', sa.BigInteger(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features_hash', sa.String(length=64), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibration_method', sa.String(length=64), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_versions_name_version')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gate_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('n_picks', sa.BigInteger(), nullable=True),
    sa.Column('roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('clv_log_mean', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sport_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('normalized_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport_id', 'normalized_name', name='uq_teams_sport_normalized')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sport_id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('external_ref', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='scheduled', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_ref', name='uq_events_external_ref')
    )
    op.create_index('idx_events_league_starts', 'events', ['league_id', 'starts_at'], unique=False)
    op.create_index('idx_events_starts_at', 'events', ['starts_at'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('probability', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'model_version_id', 'market', 'selection', name='uq_model_predictions_unique')
    )
    op.create_index('idx_predictions_event', 'model_predictions', ['event_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_closing', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'bookmaker', 'market', 'selection', 'captured_at', name='uq_odds_snapshot_observation')
    )
    op.create_index('idx_odds_event_market_captured', 'odds_snapshots', ['event_id', 'market', 'captured_at'], unique=False)
    op.create_table('detected_edges',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('model_prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('odds_snapshot_id', sa.BigInteger(), nullable=False),
    sa.Column('devig_method', sa.String(length=32), nullable=False),
    sa.Column('fair_probability', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('edge', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ev', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reject_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['model_prediction_id'], ['model_predictions.id'], ),
    sa.ForeignKeyConstraint(['odds_snapshot_id'], ['odds_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detected_edges_event', 'detected_edges', ['event_id', 'detected_at'], unique=False)
    op.create_table('picks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('detected_edge_id', sa.BigInteger(), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('decimal_odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('model_probability', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('fair_probability', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('edge', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ev', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('recommended_stake_fraction', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('recommended_stake_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stake_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closing_odds', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('closing_fair_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('clv_log', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('beat_close', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['detected_edge_id'], ['detected_edges.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'market', 'selection', 'model_version_id', name='uq_picks_event_market_selection_model')
    )
    op.create_index('idx_picks_created', 'picks', ['created_at'], unique=False)
    op.create_index('idx_picks_status', 'picks', ['status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pick_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_alerts_dedupe_key')
    )
    op.create_index('idx_alerts_pick', 'alerts', ['pick_id'], unique=False)
    op.create_table('manual_bet_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pick_id', sa.BigInteger(), nullable=False),
    sa.Column('bet_placed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('actual_stake', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_odds', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bookmaker_used', sa.String(length=64), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_manual_bet_logs_pick', 'manual_bet_logs', ['pick_id'], unique=False)
    op.create_table('result_tracking',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('pick_id', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pick_id', name='uq_result_tracking_pick')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_tracking')
    op.drop_index('idx_manual_bet_logs_pick', table_name='manual_bet_logs')
    op.drop_table('manual_bet_logs')
    op.drop_index('idx_alerts_pick', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_picks_status', table_name='picks')
    op.drop_index('idx_picks_created', table_name='picks')
    op.drop_table('picks')
    op.drop_index('idx_detected_edges_event', table_name='detected_edges')
    op.drop_table('detected_edges')
    op.drop_index('idx_odds_event_market_captured', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('idx_predictions_event', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('idx_events_starts_at', table_name='events')
    op.drop_index('idx_events_league_starts', table_name='events')
    op.drop_table('events')
    op.drop_table('teams')
    op.drop_table('backtest_runs')
    op.drop_table('model_versions')
    op.drop_table('leagues')
    op.drop_table('sports')
    op.drop_table('bankroll_snapshots')
    # ### end Alembic commands ###
