"""Drain the no-result settlement backlog using the ENGINE'S OWN expiry rules.

Background (backlog audit 2026-08-02/03): ~870 alerted picks sit past kickoff
with no result source. Root cause of persistence: nothing is broken — the
bounded expiry shipped in 8d67b61 runs every settlement cycle and voids picks
daily; the backlog is simply YOUNGER than its bounds (15d hard void / 21d gap
expiry), so it is the steady-state in-window queue. This script exists as
operator tooling for draining whatever the rules say is unresolvable RIGHT
NOW (e.g. after a settle-job outage), with the house dry-run + audit-table
convention. It adds NO policy of its own:

- Eligibility is decided by calling the 8d67b61 engine function VERBATIM —
  ``report_and_expire_no_result_picks`` (bounded gap expiry against the
  union ScoreBook, ``SETTLEMENT_EXPIRE_DAYS``): a pick expires only when NO
  source in the union book holds a candidate result for its fixture AND its
  kickoff is past the bound. The cycle's 15d hard void
  (``void_unsettleable_known_kickoff_picks``) is deliberately NOT invoked
  here: it does not consult the book (safe in the cycle only because the
  settle passes have graded book-covered picks for days beforehand), so a
  one-shot run of it could void a pick the providers CAN grade.
- Every void they perform is additionally audited into
  ``settlement_restatements`` (pick_id, column_name, old/new, reason
  'expire_unresolvable_backlog'), mirroring restate_tennis_spread_grades.py.
- OPERATOR SCOPE CARVE-OUT (2026-08-02 re-grade task): tennis
  ``market='spreads'`` picks whose ``market_detail`` does not prove the SETS
  axis are the intentionally re-opened game-handicap family awaiting a
  games-level re-grade — this script reverts (within the same transaction)
  any void the engine rules would apply to them and reports them as skipped.
- An EMPTY union book aborts: a provider outage must not look like a quiet
  day (mirrors the engine's silent-empty refusal).

Usage (dry-run is the DEFAULT — one transaction, ROLLED BACK, exact counts):

    uv run python scripts/expire_unresolvable_backlog.py
    uv run python scripts/expire_unresolvable_backlog.py --apply

Decision-support data hygiene only — this script never touches betting
execution (none exists).
"""

from __future__ import annotations

import argparse
import asyncio
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.settlement.engine import (
    EXPIRED_NO_RESULT_NOTE,
    report_and_expire_no_result_picks,
)
from app.settlement.results import ScoreBook

RESTATEMENT_REASON: Final[str] = "expire_unresolvable_backlog"
AUDIT_TABLE: Final[str] = "settlement_restatements"

# Same DDL as scripts/restate_tennis_spread_grades.py (idempotent).
_CREATE_AUDIT: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {AUDIT_TABLE} (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_id      BIGINT       NOT NULL,
    column_name  VARCHAR(64)  NOT NULL,
    old_value    TEXT,
    new_value    TEXT,
    reason       VARCHAR(128) NOT NULL,
    restated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
)
"""

# THIS RUN's voids are selected by (note, settled_at == :now): the engine
# function stamps settled_at with the exact ``now`` this script passes, plus
# the shared no-result note — precisely the rows written in this transaction,
# nothing from earlier cycles.
# The operator carve-out family: tennis game-axis (non-sets / NULL detail)
# spreads — condition copied VERBATIM from restate_tennis_spread_grades.py.
_CARVEOUT_VOIDS: Final[str] = r"""
SELECT rt.id AS rt_id, rt.pick_id
FROM result_tracking rt
JOIN picks p  ON p.id = rt.pick_id
JOIN events e ON e.id = p.event_id
JOIN sports s ON s.id = e.sport_id
WHERE rt.note = :note AND rt.settled_at = :now
  AND s.key = 'tennis'
  AND p.market = 'spreads'
  AND (
        p.market_detail IS NULL
        OR (
             lower(p.market_detail) NOT LIKE 'spreads\_sets%'
             AND NOT (
                 lower(p.market_detail) LIKE 'asian\_handicap%'
                 AND lower(p.market_detail) LIKE '%\_sets'
             )
           )
      )
"""

_REVERT_CARVEOUT_STATUS: Final[str] = """
UPDATE picks SET status = 'alerted'
WHERE id IN (SELECT pick_id FROM _eub_carveout) AND status = 'settled'
"""

_REVERT_CARVEOUT_RESULTS: Final[str] = """
DELETE FROM result_tracking WHERE id IN (SELECT rt_id FROM _eub_carveout)
"""

# One audit row per changed column for every void that STANDS after the
# carve-out revert (old_value NULL on result_tracking columns = row did not
# exist before this run).
_INSERT_AUDIT: Final[str] = f"""
INSERT INTO {AUDIT_TABLE} (pick_id, column_name, old_value, new_value, reason)
SELECT rt.pick_id, v.column_name, v.old_value, v.new_value, :reason
FROM result_tracking rt
CROSS JOIN LATERAL (VALUES
    ('picks.status',           'alerted', 'settled'),
    ('result_tracking.outcome', NULL,     'void'),
    ('result_tracking.note',    NULL,     rt.note)
) AS v(column_name, old_value, new_value)
WHERE rt.note = :note AND rt.settled_at = :now
"""  # noqa: S608 - table name is an internal literal

_EXPIRED_BY_LEAGUE: Final[str] = """
SELECT s.key, l.name, count(*)
FROM result_tracking rt
JOIN picks p  ON p.id = rt.pick_id
JOIN events e ON e.id = p.event_id
JOIN sports s ON s.id = e.sport_id
JOIN leagues l ON l.id = e.league_id
WHERE rt.note = :note AND rt.settled_at = :now
GROUP BY 1, 2 ORDER BY 3 DESC, 1, 2
"""

_REMAINING_BY_LEAGUE: Final[str] = """
SELECT s.key, l.name, count(*)
FROM picks p
JOIN events e ON e.id = p.event_id
JOIN sports s ON s.id = e.sport_id
JOIN leagues l ON l.id = e.league_id
WHERE p.status = 'alerted' AND e.starts_at IS NOT NULL AND e.starts_at < :now
GROUP BY 1, 2 ORDER BY 3 DESC, 1, 2
"""


class EmptyBookError(RuntimeError):
    """Union result book is empty — provider outage, refuse to drain."""


@dataclass(frozen=True)
class ExpiryReport:
    book_size: int
    expired_total: int
    expired_by_league: list[tuple[str, str, int]]
    skipped_tennis_game_spreads: int
    audit_rows: int
    remaining_by_league: list[tuple[str, str, int]]


async def expire_backlog(
    session: AsyncSession,
    book: ScoreBook,
    now: datetime,
    *,
    expire_after: timedelta | None,
) -> ExpiryReport:
    """Run the engine's no-result expiry rules once on an ALREADY-BEGUN
    transaction (caller owns commit/rollback), audit every standing void,
    and revert the tennis game-spread carve-out family. Returns the report."""
    if len(book) == 0:
        raise EmptyBookError("union result book is empty — provider outage, aborting")
    await session.execute(text(_CREATE_AUDIT))
    # The 8d67b61 mechanism's rule, verbatim (no new policy):
    await report_and_expire_no_result_picks(session, book, now, expire_after=expire_after)
    await session.flush()
    params = {"note": EXPIRED_NO_RESULT_NOTE, "now": now}
    # Carve-out revert (same transaction => the family is never voided).
    await session.execute(
        text(f"CREATE TEMP TABLE _eub_carveout ON COMMIT DROP AS {_CARVEOUT_VOIDS}"),  # noqa: S608
        params,
    )
    skipped = int(await session.scalar(text("SELECT count(*) FROM _eub_carveout")) or 0)
    if skipped:
        await session.execute(text(_REVERT_CARVEOUT_STATUS))
        await session.execute(text(_REVERT_CARVEOUT_RESULTS))
        # The ORM identity map may still hold these picks as 'settled';
        # expire them so any later refresh re-reads the reverted row.
        session.expire_all()
    audit_result = await session.execute(
        text(_INSERT_AUDIT), {**params, "reason": RESTATEMENT_REASON}
    )
    audit_rows = int(getattr(audit_result, "rowcount", 0) or 0)
    expired_by_league = [
        (str(sport), str(league), int(n))
        for sport, league, n in (await session.execute(text(_EXPIRED_BY_LEAGUE), params)).all()
    ]
    remaining_by_league = [
        (str(sport), str(league), int(n))
        for sport, league, n in (
            await session.execute(text(_REMAINING_BY_LEAGUE), {"now": now})
        ).all()
    ]
    return ExpiryReport(
        book_size=len(book),
        expired_total=sum(n for *_, n in expired_by_league),
        expired_by_league=expired_by_league,
        skipped_tennis_game_spreads=skipped,
        audit_rows=audit_rows,
        remaining_by_league=remaining_by_league,
    )


async def run(*, apply: bool) -> None:
    import httpx

    from app.config import get_settings
    from app.database import create_engine
    from app.settlement.engine import _load_feed_scores, _load_scraped_finals

    settings = get_settings()
    now = datetime.now(tz=UTC)
    slugs = [s.strip() for s in settings.oddsportal_football_leagues.split(",") if s.strip()]
    seasons = [s.strip() for s in settings.footballdata_seasons.split(",") if s.strip()]
    expire_after = (
        timedelta(days=settings.settlement_expire_days)
        if settings.settlement_expire_days > 0
        else None
    )
    engine = create_engine(settings)
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            feed_scores = await _load_feed_scores(client, slugs, seasons, now, settings)
        async with AsyncSession(engine, expire_on_commit=False) as session, session.begin():
            scraped = (
                await _load_scraped_finals(session, now)
                if settings.settle_from_scraped_scores
                else []
            )
            report = await expire_backlog(
                session,
                ScoreBook([*feed_scores, *scraped]),
                now,
                expire_after=expire_after,
            )
            mode = "APPLY" if apply else "DRY-RUN (rolled back)"
            print(f"\n=== no-result backlog expiry — {mode} ===")
            print(f"reason: {RESTATEMENT_REASON}  |  union book: {report.book_size} scores")
            print(
                f"\n  expired (voided) total: {report.expired_total}"
                f"  |  audit rows: {report.audit_rows}"
                f"  |  skipped tennis game-spreads (re-grade scope): "
                f"{report.skipped_tennis_game_spreads}"
            )
            if report.expired_by_league:
                print("\n  expired by sport/league:")
                for sport, league, n in report.expired_by_league:
                    print(f"    {sport}/{league}: {n}")
            print("\n  still open past kickoff (younger than the bounds — the cycle")
            print("  will expire each at its bound):")
            for sport, league, n in report.remaining_by_league[:15]:
                print(f"    {sport}/{league}: {n}")
            if not apply:
                raise _Rollback
    except _Rollback:
        pass
    finally:
        await engine.dispose()


class _Rollback(Exception):
    """Unwinds the session.begin() block so the dry-run rolls back."""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="commit the expiry (default: dry-run, rolled back)",
    )
    args = parser.parse_args()
    asyncio.run(run(apply=args.apply))


if __name__ == "__main__":
    main()
