"""Zandschulo-cascade event audit: dedup-replay + conditional close quarantine.

Background (verified against prod 2026-08-06): the OddsChecker slug typo
``botic-van-de-zandschulo`` recurs across five live-namespace tennis events
(14908, 15093, 20455, 21539, 22178). The reviewed alias batch 2026-08-06
('zandschulo b'/'vandezandschulo b' -> 'zandschulp b') pre-empts further
false-positive wrong_game_anchor ERRORs and makes future matches exact.

MERGE VERDICT — REFUSED, with evidence. Event 21582 (external_ref 1633360522)
was reported as "a Pinnacle-ref duplicate of 21539". It is NOT a duplicate
canonical event: it lives in the ``pinnacle_tennis`` sport namespace — the
arcadia archive's deliberately ISOLATED warehouse namespace (7,566 events;
every arcadia-captured fixture has such a twin, e.g. 14711, 19754). The
sanctioned canonical-event dedup/merge path (PR2b,
docs/review/pr2b_event_merge_2026_07_10.sql) clusters on the EXACT oriented
key ``(sport_id, home_team_id, away_team_id)`` and therefore can never — by
design — group a pinnacle_* archive row with its live twin. Anchor resolution
already links the pair via event_source_links (row 345777, pinnacle_arcadia
ref 1633360522 -> canonical 21539, jw_two_tier 0.96; corroborated by row
344185, betfair_api ref 35904471). Merging 21582 into 21539 would destroy the
archive isolation the wrong-game audit and sharp-anchor path depend on, so
this script REPLAYS the PR2b clustering over the named events (read-only) and
asserts it yields ZERO merge groups. If it ever reports a nonzero count, run
the canonical PR2b SQL — this script never hand-rolls a merge.

QUARANTINE — pick 960690 (event 21539, totals Under 2.5, minted 23:14:07 UTC,
14 minutes POST-KICKOFF). Per instruction the wrong_game-style close re-null
(every close column NULL + ``close_exclusion_reason``) applies ONLY if a close
was stamped; as of 2026-08-06 all close columns are NULL, so the dry run
reports "no close stamped — nothing to quarantine". If a close lands before
this is executed, ``--apply`` re-nulls it with
``close_exclusion_reason='postko_dup_mint'`` and preserves the old values in
the ``bookmaker_label_restatements`` audit table (the 2026-08-02 close-re-null
precedent), reason ``postko_mint_close_renull``.

HISTORICAL REPORT (read-only): 14908/20455 carry no picks; 15093's five picks
are settled void with no closes — all left as history. 22178 (2026-08-07 vs
Hurkacz) needs no data change; the alias fix covers its re-mint.

Usage (dry-run is the DEFAULT — one transaction, rolled back, exact counts):

    uv run python scripts/merge_zandschulo_duplicates.py
    uv run python scripts/merge_zandschulo_duplicates.py --apply

Run with the scheduler stopped for --apply. Decision-support data hygiene only
— this script never touches betting execution (none exists).
"""

from __future__ import annotations

import argparse
import asyncio
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

from app.config import get_settings
from app.database import create_engine

#: The five typo'd live-namespace events plus the arcadia archive twin.
CASCADE_EVENT_IDS: Final[tuple[int, ...]] = (14908, 15093, 20455, 21539, 21582, 22178)

#: The post-kickoff-minted pick on canonical event 21539.
QUARANTINE_PICK_ID: Final[int] = 960690
QUARANTINE_EVENT_ID: Final[int] = 21539

#: VARCHAR(32) — the honest reason: the mint was post-kickoff on the cascade
#: event; the anchor itself was the CORRECT fixture (not wrong_game).
CLOSE_EXCLUSION_REASON: Final[str] = "postko_dup_mint"

AUDIT_TABLE: Final[str] = "bookmaker_label_restatements"

_CREATE_AUDIT: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {AUDIT_TABLE} (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   VARCHAR(64)  NOT NULL,
    row_id       BIGINT       NOT NULL,
    column_name  VARCHAR(64)  NOT NULL,
    old_label    VARCHAR(512),
    new_label    VARCHAR(512),
    reason       VARCHAR(128) NOT NULL,
    details      JSONB,
    restated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
)
"""

# EXACT replay of the PR2b gap-and-island clustering
# (docs/review/pr2b_event_merge_2026_07_10.sql), restricted to the cascade
# events. The oriented key (sport_id, home_team_id, away_team_id) is the
# sanctioned dedup identity — a pinnacle_* archive twin has a DIFFERENT
# sport_id (isolated namespace) and team ids, so it can never cluster with its
# live event. Expected result: 0 merge groups.
_PR2B_CLUSTER_REPLAY: Final[str] = """
WITH ordered AS (
  SELECT e.id, e.sport_id, s.key AS sport, e.starts_at, e.home_team_id, e.away_team_id,
         lag(e.starts_at) OVER (
           PARTITION BY e.sport_id, e.home_team_id, e.away_team_id ORDER BY e.starts_at
         ) AS prev_start
  FROM events e JOIN sports s ON s.id = e.sport_id
  WHERE e.id = ANY(:event_ids)
),
flagged AS (
  SELECT *,
         CASE WHEN prev_start IS NULL
                OR abs(extract(epoch FROM (starts_at - prev_start)))
                   > (CASE WHEN sport = 'tennis' THEN 21600 ELSE 7200 END)
              THEN 1 ELSE 0 END AS newcluster
  FROM ordered
),
clustered AS (
  SELECT id, sport_id, home_team_id, away_team_id,
         sum(newcluster) OVER (
           PARTITION BY sport_id, home_team_id, away_team_id
           ORDER BY starts_at ROWS UNBOUNDED PRECEDING
         ) AS cl
  FROM flagged
)
SELECT count(*) AS merge_groups
FROM (
  SELECT 1 FROM clustered
  GROUP BY sport_id, home_team_id, away_team_id, cl
  HAVING count(*) > 1
) g
"""

_EVENT_REPORT: Final[str] = """
SELECT e.id, s.key AS sport, e.external_ref, e.starts_at,
       ht.name AS home, at.name AS away,
       (SELECT count(*) FROM picks p WHERE p.event_id = e.id) AS picks,
       (SELECT count(*) FROM odds_snapshots o WHERE o.event_id = e.id) AS snaps,
       (SELECT count(*) FROM event_source_links l
         WHERE l.canonical_event_id = e.id AND l.active) AS links
FROM events e
JOIN sports s ON s.id = e.sport_id
JOIN teams ht ON ht.id = e.home_team_id
JOIN teams at ON at.id = e.away_team_id
WHERE e.id = ANY(:event_ids)
ORDER BY e.starts_at
"""

_PICK_REPORT: Final[str] = """
SELECT p.id, p.event_id, p.status, p.market, p.selection, p.created_at,
       p.closing_odds, p.close_anchor_book, p.close_exclusion_reason,
       rt.outcome
FROM picks p LEFT JOIN result_tracking rt ON rt.pick_id = p.id
WHERE p.event_id = ANY(:event_ids)
ORDER BY p.event_id, p.id
"""

# wrong_game-precedent re-null (state shape of restate_oddschecker_betfair_
# labels.py): fires ONLY when a close is actually stamped; old values are
# preserved in the audit row's details jsonb.
_RENULL_SQL: Final[str] = f"""
WITH sel AS (
    SELECT id, jsonb_build_object(
        'closing_odds', closing_odds,
        'closing_fair_probability', closing_fair_probability,
        'clv_log', clv_log,
        'beat_close', beat_close,
        'closing_anchor_type', closing_anchor_type,
        'close_anchor_book', close_anchor_book,
        'close_snapshot_captured_at', close_snapshot_captured_at,
        'has_snapshot_close', has_snapshot_close,
        'close_independent_of_fill', close_independent_of_fill,
        'prior_close_exclusion_reason', close_exclusion_reason
    ) AS d
    FROM picks
    WHERE id = :pick_id
      AND event_id = :event_id
      AND (closing_odds IS NOT NULL
           OR closing_fair_probability IS NOT NULL
           OR clv_log IS NOT NULL
           OR close_snapshot_captured_at IS NOT NULL)
    FOR UPDATE
), upd AS (
    UPDATE picks p SET
        closing_odds = NULL,
        closing_fair_probability = NULL,
        clv_log = NULL,
        beat_close = NULL,
        closing_anchor_type = NULL,
        close_anchor_book = NULL,
        close_snapshot_captured_at = NULL,
        has_snapshot_close = NULL,
        close_independent_of_fill = NULL,
        close_exclusion_reason = :reason
    FROM sel WHERE p.id = sel.id
    RETURNING p.id
)
INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
    old_label, new_label, reason, details)
SELECT 'picks', sel.id, 'close_exclusion_reason', NULL,
       CAST(:reason AS varchar), 'postko_mint_close_renull', sel.d
FROM sel JOIN upd ON upd.id = sel.id
"""  # noqa: S608 - table name is an internal literal


async def _replay_pr2b_clustering(conn: AsyncConnection) -> int:
    result = await conn.execute(text(_PR2B_CLUSTER_REPLAY), {"event_ids": list(CASCADE_EVENT_IDS)})
    return int(result.scalar_one())


async def run(*, apply: bool) -> int:
    engine = create_engine(get_settings())
    try:
        async with engine.connect() as conn:
            trans = await conn.begin()
            await conn.execute(text(_CREATE_AUDIT))

            mode = "APPLY" if apply else "DRY-RUN (rolled back)"
            print(f"\n=== Zandschulo cascade audit — {mode} ===\n")

            # ---- read-only event report --------------------------------
            print("-- cascade events --")
            rows = (
                await conn.execute(text(_EVENT_REPORT), {"event_ids": list(CASCADE_EVENT_IDS)})
            ).all()
            for r in rows:
                print(
                    f"  event {r.id:>5}  [{r.sport}]  {r.home!r} v {r.away!r} "
                    f"@ {r.starts_at:%Y-%m-%d %H:%M}Z  picks={r.picks} "
                    f"snaps={r.snaps} active_links={r.links}  ref={r.external_ref}"
                )

            # ---- PR2b dedup replay (the sanctioned merge identity) -----
            groups = await _replay_pr2b_clustering(conn)
            print(f"\n-- PR2b oriented-key merge groups among these events: {groups} --")
            if groups == 0:
                print(
                    "  0 groups, as designed: 21582 is the pinnacle_tennis ARCADIA\n"
                    "  archive twin of 21539 (isolated warehouse namespace; linked via\n"
                    "  event_source_links 345777 at 0.96), NOT a duplicate canonical\n"
                    "  event. NO merge is performed — merging across the archive\n"
                    "  namespace would break anchor/audit isolation."
                )
            else:
                print(
                    "  NONZERO groups found — do NOT merge here. Run the canonical\n"
                    "  PR2b migration (docs/review/pr2b_event_merge_2026_07_10.sql)\n"
                    "  which owns the online no-pause merge semantics."
                )

            # ---- pick report + conditional close quarantine ------------
            print("\n-- picks on cascade events --")
            picks = (
                await conn.execute(text(_PICK_REPORT), {"event_ids": list(CASCADE_EVENT_IDS)})
            ).all()
            for p in picks:
                close = (
                    f"close={p.closing_odds} book={p.close_anchor_book}"
                    if p.closing_odds is not None
                    else "no close"
                )
                print(
                    f"  pick {p.id:>7}  ev={p.event_id}  {p.status:<9} "
                    f"{p.market}/{p.selection}  outcome={p.outcome or '-'}  {close}"
                    f"  excl={p.close_exclusion_reason or '-'}"
                )

            renulled = int(
                (
                    await conn.execute(
                        text(_RENULL_SQL),
                        {
                            "pick_id": QUARANTINE_PICK_ID,
                            "event_id": QUARANTINE_EVENT_ID,
                            "reason": CLOSE_EXCLUSION_REASON,
                        },
                    )
                ).rowcount
                or 0
            )
            if renulled:
                print(
                    f"\n-- pick {QUARANTINE_PICK_ID}: close RE-NULLED "
                    f"(close_exclusion_reason='{CLOSE_EXCLUSION_REASON}', "
                    "old values in audit details) --"
                )
            else:
                print(
                    f"\n-- pick {QUARANTINE_PICK_ID}: no close stamped — "
                    "nothing to quarantine (per instruction, mark nothing) --"
                )

            print(
                "\n-- historical events 14908/20455 (no picks) and 15093 (5 settled\n"
                "   void picks, no closes) are left as history; 22178 (2026-08-07 vs\n"
                "   Hurkacz) is covered by the 2026-08-06 alias batch. --"
            )

            if apply:
                await trans.commit()
                print(f"\nCOMMITTED. Close re-nulls: {renulled}.")
            else:
                await trans.rollback()
                print(f"\nROLLED BACK (dry run). Close re-nulls that WOULD apply: {renulled}.")
            return renulled
    finally:
        await engine.dispose()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute for real (default is dry-run: run everything, print counts, roll back).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(run(apply=_parse_args().apply))
