"""Restate gross-settled exchange-fill P&L to commission-net (2026-08-02).

Background (operator-approved follow-up to the bookmaker-label restatement,
scripts/restate_oddschecker_betfair_labels.py): 1,285 pick fills were
relabeled 'Betfair Sportsbook' -> 'Betfair Exchange' — they were REAL
exchange fills all along. Because the mislabel bypassed EXCHANGE_COMMISSION
(app/edge/value.py), their settlements were booked GROSS: for 1,050 of the
1,052 settled rows result_tracking.settled_effective_odds equals
picks.decimal_odds and winning P&L never had the 5% Betfair commission on
net winnings deducted.

Scope: picks restated to 'Betfair Exchange' by the label restatement
(bookmaker_label_restatements table_name='picks', column_name='bookmaker',
new_label='Betfair Exchange') AND settled won/half_won AND still
gross-settled (settled_effective_odds == decimal_odds). The 2 repriced rows
(effective odds already != decimal odds) are excluded — never
double-corrected — and the criterion also makes re-runs naturally
idempotent.

Correction reuses the LIVE settlement code, never a reimplementation:
``app.settlement.engine._effective_settlement_odds`` (-> ``effective_odds``
in app/edge/value.py: 1 + (odds-1)*(1-0.05)) for the netted price, and
``app.settlement.outcomes.pick_pnl`` / ``pick_roi`` for the corrected
won/half_won P&L and ROI at the stored settled stake. All money math is
Decimal end-to-end (the reused live functions define the canonical formula,
float only where they themselves use it).

Audit: every changed column lands in ``pnl_restatements`` (one row per
changed column per pick, old value preserved -> fully reversible) with
reason 'exchange_commission_unnetted'.

Usage (dry-run is the DEFAULT — executes everything in one transaction and
ROLLS BACK, printing per-column counts, total P&L delta, and before/after
tier ROI):

    uv run python scripts/restate_exchange_commission_pnl.py
    uv run python scripts/restate_exchange_commission_pnl.py --apply

Run with the scheduler stopped. Decision-support data hygiene only — this
script never touches betting execution (none exists).
"""

from __future__ import annotations

import argparse
import asyncio
from dataclasses import dataclass
from decimal import Decimal
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

from app.config import get_settings
from app.database import create_engine
from app.settlement.engine import _effective_settlement_odds
from app.settlement.outcomes import Outcome, pick_pnl, pick_roi

# The corrected book label the label restatement established for these fills;
# keys the EXCHANGE_COMMISSION table (5% on net winnings) inside the reused
# live functions.
EXCHANGE_BOOK: Final[str] = "Betfair Exchange"

REASON: Final[str] = "exchange_commission_unnetted"

AUDIT_TABLE: Final[str] = "pnl_restatements"

# Column-storage quantums (app/storage/models.py: ODDS Numeric(10,4),
# MONEY Numeric(12,2), METRIC Numeric(12,6)) — audit old/new values must
# match what the columns actually store, or reversal drifts.
_Q_ODDS: Final[Decimal] = Decimal("0.0001")
_Q_METRIC: Final[Decimal] = Decimal("0.000001")

_CREATE_AUDIT: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {AUDIT_TABLE} (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_id      BIGINT       NOT NULL,
    column_name  VARCHAR(64)  NOT NULL,
    old_value    NUMERIC,
    new_value    NUMERIC,
    reason       VARCHAR(128) NOT NULL,
    restated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
)
"""

# Gross-settled winning fills among the label-restated cohort. FOR UPDATE OF
# rt: rows are corrected in this same transaction. The settled_effective_odds
# = decimal_odds predicate excludes the repriced rows AND makes an accidental
# second --apply a no-op.
_SELECT_TARGETS: Final[str] = """
SELECT p.id AS pick_id, rt.id AS rt_id, rt.outcome,
       rt.settled_stake_amount, p.decimal_odds,
       rt.pnl, rt.roi, rt.settled_effective_odds
FROM picks p
JOIN result_tracking rt ON rt.pick_id = p.id
WHERE rt.outcome IN ('won', 'half_won')
  AND rt.settled_effective_odds = p.decimal_odds
  AND EXISTS (
      SELECT 1 FROM bookmaker_label_restatements r
      WHERE r.table_name = 'picks' AND r.column_name = 'bookmaker'
        AND r.new_label = :book AND r.row_id = p.id
  )
ORDER BY p.id
FOR UPDATE OF rt
"""

_UPDATE_RT: Final[str] = """
UPDATE result_tracking
SET settled_effective_odds = :eff, pnl = :pnl, roi = :roi
WHERE id = :rt_id
"""

_INSERT_AUDIT: Final[str] = f"""
INSERT INTO {AUDIT_TABLE} (pick_id, column_name, old_value, new_value, reason)
VALUES (:pick_id, :column_name, :old_value, :new_value, :reason)
"""  # noqa: S608 - table name is an internal literal

# Settled ROI by tier (pnl and stake basis identical to the read-only audit:
# actual settled stake, else the recommendation).
_ROI_BY_TIER: Final[str] = """
SELECT COALESCE(p.tier, '(none)') AS tier,
       SUM(rt.pnl) AS pnl,
       SUM(COALESCE(rt.settled_stake_amount, p.recommended_stake_amount)) AS staked
FROM picks p
JOIN result_tracking rt ON rt.pick_id = p.id
WHERE rt.pnl IS NOT NULL
GROUP BY 1
ORDER BY 1
"""


@dataclass(frozen=True)
class ColumnChange:
    pick_id: int
    column_name: str
    old_value: Decimal | None
    new_value: Decimal | None


async def _tier_roi(conn: AsyncConnection) -> dict[str, tuple[Decimal, Decimal]]:
    rows = (await conn.execute(text(_ROI_BY_TIER))).all()
    return {r.tier: (Decimal(r.pnl), Decimal(r.staked)) for r in rows}


def _fmt_roi(pnl: Decimal, staked: Decimal) -> str:
    if staked == 0:
        return "n/a (0 staked)"
    return f"{pnl / staked:+.4%}"


def _print_roi_delta(
    before: dict[str, tuple[Decimal, Decimal]],
    after: dict[str, tuple[Decimal, Decimal]],
) -> None:
    tiers = sorted(before.keys() | after.keys())
    print("\n  settled ROI (pnl / staked) before -> after:")
    all_b = (
        sum((v[0] for v in before.values()), Decimal(0)),
        sum((v[1] for v in before.values()), Decimal(0)),
    )
    all_a = (
        sum((v[0] for v in after.values()), Decimal(0)),
        sum((v[1] for v in after.values()), Decimal(0)),
    )
    for tier in tiers:
        b_pnl, b_stk = before.get(tier, (Decimal(0), Decimal(0)))
        a_pnl, a_stk = after.get(tier, (Decimal(0), Decimal(0)))
        print(
            f"    {tier:<10} pnl {b_pnl:>10.2f} -> {a_pnl:>10.2f}   "
            f"roi {_fmt_roi(b_pnl, b_stk):>9} -> {_fmt_roi(a_pnl, a_stk):>9}"
        )
    print(
        f"    {'ALL':<10} pnl {all_b[0]:>10.2f} -> {all_a[0]:>10.2f}   "
        f"roi {_fmt_roi(*all_b):>9} -> {_fmt_roi(*all_a):>9}"
    )


def _corrections(
    row: object,
) -> tuple[list[ColumnChange], dict[str, object], Decimal]:
    """Corrected values for one gross-settled winning fill.

    Returns (audit changes, update params, pnl delta). Every formula is the
    LIVE code: _effective_settlement_odds for the price, pick_pnl/pick_roi
    for the money — half_won is handled inside pick_pnl exactly as the
    settlement engine settles it.
    """
    pick_id = int(row.pick_id)  # type: ignore[attr-defined]
    outcome = Outcome(row.outcome)  # type: ignore[attr-defined]
    stake: Decimal = row.settled_stake_amount  # type: ignore[attr-defined]
    decimal_odds: Decimal = row.decimal_odds  # type: ignore[attr-defined]
    old_pnl: Decimal = row.pnl  # type: ignore[attr-defined]
    old_roi: Decimal | None = row.roi  # type: ignore[attr-defined]
    old_eff: Decimal = row.settled_effective_odds  # type: ignore[attr-defined]

    new_eff = _effective_settlement_odds(decimal_odds, EXCHANGE_BOOK).quantize(_Q_ODDS)
    new_pnl = pick_pnl(outcome, stake, decimal_odds, bookmaker=EXCHANGE_BOOK)
    raw_roi = pick_roi(new_pnl, stake)
    new_roi = raw_roi.quantize(_Q_METRIC) if raw_roi is not None else None

    # Sanity: netting a winning fill can only shave the price and the profit.
    if new_eff >= old_eff or new_pnl > old_pnl:
        raise AssertionError(
            f"pick {pick_id}: correction not a reduction "
            f"(eff {old_eff}->{new_eff}, pnl {old_pnl}->{new_pnl})"
        )

    changes = [ColumnChange(pick_id, "settled_effective_odds", old_eff, new_eff)]
    if new_pnl != old_pnl:
        changes.append(ColumnChange(pick_id, "pnl", old_pnl, new_pnl))
    if new_roi != old_roi:
        changes.append(ColumnChange(pick_id, "roi", old_roi, new_roi))
    params: dict[str, object] = {
        "rt_id": int(row.rt_id),  # type: ignore[attr-defined]
        "eff": new_eff,
        "pnl": new_pnl,
        "roi": new_roi,
    }
    return changes, params, new_pnl - old_pnl


async def run(*, apply: bool) -> None:
    engine = create_engine(get_settings())
    try:
        async with engine.connect() as conn:
            trans = await conn.begin()
            await conn.execute(text(_CREATE_AUDIT))

            roi_before = await _tier_roi(conn)
            rows = (await conn.execute(text(_SELECT_TARGETS), {"book": EXCHANGE_BOOK})).all()

            all_changes: list[ColumnChange] = []
            updates: list[dict[str, object]] = []
            total_delta = Decimal(0)
            for row in rows:
                changes, params, delta = _corrections(row)
                all_changes.extend(changes)
                updates.append(params)
                total_delta += delta

            if updates:
                await conn.execute(text(_UPDATE_RT), updates)
                await conn.execute(
                    text(_INSERT_AUDIT),
                    [
                        {
                            "pick_id": c.pick_id,
                            "column_name": c.column_name,
                            "old_value": c.old_value,
                            "new_value": c.new_value,
                            "reason": REASON,
                        }
                        for c in all_changes
                    ],
                )

            roi_after = await _tier_roi(conn)

            mode = "APPLY" if apply else "DRY-RUN (rolled back)"
            print(f"\n=== exchange-commission P&L restatement — {mode} ===")
            print(f"target: gross-settled won/half_won fills relabeled to '{EXCHANGE_BOOK}'\n")
            by_col = {
                col: sum(1 for c in all_changes if c.column_name == col)
                for col in ("settled_effective_odds", "pnl", "roi")
            }
            print(f"  picks corrected:                        {len(updates):>7}")
            for col, n in by_col.items():
                print(f"  result_tracking.{col:<24}changed {n:>7}")
            zero_stake = len(updates) - by_col["pnl"]
            print(f"  (zero-stake winners, price-only fix):   {zero_stake:>7}")
            print(f"  audit rows ({AUDIT_TABLE}):        {len(all_changes):>7}")
            print(f"\n  total P&L delta: {total_delta:+.2f}")
            _print_roi_delta(roi_before, roi_after)

            if apply:
                await trans.commit()
                print(f"\nCOMMITTED. Audit rows in {AUDIT_TABLE}.")
            else:
                await trans.rollback()
                print("\nROLLED BACK (dry run). Re-run with --apply to execute.")
    finally:
        await engine.dispose()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute for real (default is dry-run: run everything, print counts, roll back).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(run(apply=_parse_args().apply))
