"""Restate OddsChecker-era mislabeled Betfair bookmaker labels (2026-08-02).

Background (forensics 2026-08-02, operator-approved restatement):
OddsChecker RECYCLED bookmaker codes — code ``BF`` is the real Betfair
EXCHANGE and code ``OE`` is the traditional book 10bet. The static fallback
map introduced at e154b6e (2026-07-05 13:15 UTC, the commit that made
oddschecker the default odds source) had these INVERTED, and the persisting
all-odds path always resolved via the fallbacks. The map was wrong for the
ENTIRE oddschecker era — first mislabeled row 2026-07-01 (pre-default test
cycles), fixed by c611bc5 deployed from the worktree ~2026-08-02 13:00 UTC.

Mislabel classes (window = [2026-07-01, fix deploy)):
  1. ``Betfair Sportsbook``  -> ``Betfair Exchange``  (code BF, real exchange)
  2. ``Betfair`` (bare)      -> ``Betfair Exchange``  (code BF, M863 era)
  3. ``Betfair Exchange``    -> ``10bet``             (code OE, soft book)

Class 3 is scoped to rows the oddschecker pipeline wrote: liquidity IS NULL
and captured after the oddsportal cutover (2026-07-05 13:18:39 UTC, the last
oddsportal row), plus the 07-01..cutover overlap slice where the market is
NOT in the oddsportal vocabulary AND the event shows same-day oddschecker
sibling evidence (a ``Betfair Sportsbook`` row). Overlap rows without sibling
evidence are logged as ambiguous, NOT restated (possible odds_api-era genuine
exchange rows). Pre-2026-07-01 ``Betfair Exchange`` rows are genuine
(oddsportal provider 44 / The Odds API betfair_ex_* / dedicated capture) and
are never touched.

Cascades: picks (bookmaker, current_bookmaker, anchor_book,
settlement_basis_bookmaker, close_anchor_book), candidate_evaluations
(anchor_book, best_book), manual_bet_logs (bookmaker_used). Raw snapshots are
RELABELED only (append-only rows are never deleted); every change lands in
the ``bookmaker_label_restatements`` audit table with the old value preserved.

Trusted-CLV contamination: picks whose stored close was anchored on the
mislabeled ``Betfair Exchange`` (really 10bet — phantom exchange-commission
netting) get the wrong_game-precedent re-null: every close column NULL and
``close_exclusion_reason='book_mislabel'`` (state shape of picks 1585/2307/…;
old values preserved in the audit row's ``details`` jsonb).

Usage (dry-run is the DEFAULT — executes everything in one transaction and
ROLLS BACK, printing exact per-table counts):

    uv run python scripts/restate_oddschecker_betfair_labels.py
    uv run python scripts/restate_oddschecker_betfair_labels.py --apply
    uv run python scripts/restate_oddschecker_betfair_labels.py \
        --fix-deployed-at 2026-08-02T13:00:00+00:00

Run with the scheduler stopped. Decision-support data hygiene only — this
script never touches betting execution (none exists).
"""

from __future__ import annotations

import argparse
import asyncio
from datetime import UTC, datetime
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

from app.config import get_settings
from app.database import create_engine

# First row written by the inverted fallback map (pre-default oddschecker
# test cycles; first 'Betfair Sportsbook' snapshot is 2026-07-01).
WINDOW_START: Final[datetime] = datetime(2026, 7, 1, tzinfo=UTC)

# Last oddsportal-written snapshot (Betano.uk/Unibetuk/BetUK all stop at this
# exact stamp — the e154b6e deploy). After this, every 'Betfair Exchange' row
# with liquidity IS NULL is oddschecker code OE = 10bet.
ODDSPORTAL_CUTOVER: Final[datetime] = datetime(2026, 7, 5, 13, 18, 39, tzinfo=UTC)

# c611bc5 went live from the worktree between 13:00 and 13:10 UTC (label mix
# flips: 'Betfair Sportsbook' collapses 12:50->13:00, '10bet' appears 13:10).
# Conservative default; override with --fix-deployed-at if host logs give a
# better stamp. Residual ambiguity is ~tens of rows in 13:00-13:10.
DEFAULT_FIX_DEPLOYED_AT: Final[datetime] = datetime(2026, 8, 2, 13, 0, tzinfo=UTC)

AUDIT_TABLE: Final[str] = "bookmaker_label_restatements"

_CREATE_AUDIT: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {AUDIT_TABLE} (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   VARCHAR(64)  NOT NULL,
    row_id       BIGINT       NOT NULL,
    column_name  VARCHAR(64)  NOT NULL,
    old_label    VARCHAR(512),
    new_label    VARCHAR(512),
    reason       VARCHAR(128) NOT NULL,
    details      JSONB,
    restated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
)
"""

# OddsPortal market vocabulary, derived from bookmakers that ONLY the
# oddsportal static map produces (used to split the 07-01..cutover overlap).
_CREATE_OP_VOCAB: Final[str] = """
CREATE TEMP TABLE _op_vocab ON COMMIT DROP AS
SELECT DISTINCT market FROM odds_snapshots
WHERE bookmaker IN ('Betano.uk', 'Unibetuk', 'BetUK')
"""

# (column, old_label, new_label, window_start_key) — column names are
# internal literals, never user input. BEX->10bet mappings start at the
# oddsportal cutover so genuine pre-cutover exchange anchors are untouched.
# ORDER MATTERS (dry-run 2026-08-02 caught a double-hop): the
# BEX->10bet relabel MUST run before BSB/bare->BEX for each column, or the
# rows just relabeled to "Betfair Exchange" are immediately re-relabeled to
# 10bet (mirrors the snapshot section's safe order).
_PICK_LABEL_MAPPINGS: Final[tuple[tuple[str, str, str, str], ...]] = (
    ("bookmaker", "Betfair Exchange", "10bet", "cutover"),
    ("bookmaker", "Betfair Sportsbook", "Betfair Exchange", "win"),
    ("bookmaker", "Betfair", "Betfair Exchange", "win"),
    ("current_bookmaker", "Betfair Exchange", "10bet", "cutover"),
    ("current_bookmaker", "Betfair Sportsbook", "Betfair Exchange", "win"),
    ("current_bookmaker", "Betfair", "Betfair Exchange", "win"),
    ("settlement_basis_bookmaker", "Betfair Exchange", "10bet", "cutover"),
    ("settlement_basis_bookmaker", "Betfair Sportsbook", "Betfair Exchange", "win"),
    ("settlement_basis_bookmaker", "Betfair", "Betfair Exchange", "win"),
    ("anchor_book", "Betfair Exchange", "10bet", "cutover"),
    ("anchor_book", "Betfair Sportsbook", "Betfair Exchange", "win"),
)

_CE_LABEL_MAPPINGS: Final[tuple[tuple[str, str, str, str], ...]] = (
    ("anchor_book", "Betfair Exchange", "10bet", "cutover"),
    ("anchor_book", "Betfair Sportsbook", "Betfair Exchange", "win"),
    ("best_book", "Betfair Exchange", "10bet", "cutover"),
    ("best_book", "Betfair Sportsbook", "Betfair Exchange", "win"),
    ("best_book", "Betfair", "Betfair Exchange", "win"),
)

_MBL_LABEL_MAPPINGS: Final[tuple[tuple[str, str, str, str], ...]] = (
    ("bookmaker_used", "Betfair Exchange", "10bet", "cutover"),
    ("bookmaker_used", "Betfair Sportsbook", "Betfair Exchange", "win"),
)


def _snapshot_relabel_sql(*, extra_where: str, reason: str) -> str:
    """Conflict-guarded snapshot relabel + audit insert in one statement.

    The NOT EXISTS guard skips rows whose relabel would collide with the
    uq_odds_snapshot_observation unique constraint (collisions are separately
    counted and audit-logged as not-restated).
    """
    return f"""
    WITH upd AS (
        UPDATE odds_snapshots os SET bookmaker = :new_label
        WHERE os.bookmaker = :old_label
          {extra_where}
          AND NOT EXISTS (
              SELECT 1 FROM odds_snapshots t
              WHERE t.event_id = os.event_id AND t.bookmaker = :new_label
                AND t.market = os.market AND t.selection = os.selection
                AND t.captured_at = os.captured_at
          )
        RETURNING os.id
    )
    INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason)
    SELECT 'odds_snapshots', id, 'bookmaker',
           CAST(:old_label AS varchar), CAST(:new_label AS varchar),
           CAST(:reason AS varchar)
    FROM upd
    """  # noqa: S608 - table/where fragments are internal literals


def _snapshot_conflict_log_sql(*, extra_where: str) -> str:
    """Audit-log (applied=false) rows left mislabeled due to unique conflicts."""
    return f"""
    INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason, details)
    SELECT 'odds_snapshots', os.id, 'bookmaker',
           CAST(:old_label AS varchar), CAST(:new_label AS varchar),
           CAST(:reason AS varchar),
           jsonb_build_object('applied', false)
    FROM odds_snapshots os
    WHERE os.bookmaker = :old_label
      {extra_where}
      AND EXISTS (
          SELECT 1 FROM odds_snapshots t
          WHERE t.event_id = os.event_id AND t.bookmaker = :new_label
            AND t.market = os.market AND t.selection = os.selection
            AND t.captured_at = os.captured_at
      )
    """  # noqa: S608


async def _exec_count(conn: AsyncConnection, sql: str, params: dict[str, object]) -> int:
    result = await conn.execute(text(sql), params)
    return int(result.rowcount or 0)


async def run(*, apply: bool, fix_deployed_at: datetime) -> None:
    engine = create_engine(get_settings())
    counts: list[tuple[str, int]] = []
    base: dict[str, object] = {
        "win": WINDOW_START,
        "cutover": ODDSPORTAL_CUTOVER,
        "fix": fix_deployed_at,
    }
    try:
        async with engine.connect() as conn:
            trans = await conn.begin()
            await conn.execute(text(_CREATE_AUDIT))
            await conn.execute(text(_CREATE_OP_VOCAB))

            # --- odds_snapshots: class 3 first (BEX->10bet must run BEFORE
            # BSB->BEX creates new 'Betfair Exchange' rows, and the overlap
            # sibling test must run while 'Betfair Sportsbook' rows exist).
            bulk_where = """
              AND os.liquidity IS NULL
              AND os.captured_at > :cutover AND os.captured_at < :fix
            """
            n = await _exec_count(
                conn,
                _snapshot_relabel_sql(extra_where=bulk_where, reason="book_mislabel_oe_recycle"),
                {
                    **base,
                    "old_label": "Betfair Exchange",
                    "new_label": "10bet",
                    "reason": "book_mislabel_oe_recycle",
                },
            )
            counts.append(("odds_snapshots: 'Betfair Exchange'->'10bet' (post-cutover)", n))
            n = await _exec_count(
                conn,
                _snapshot_conflict_log_sql(extra_where=bulk_where),
                {
                    **base,
                    "old_label": "Betfair Exchange",
                    "new_label": "10bet",
                    "reason": "book_mislabel_conflict_not_restated",
                },
            )
            counts.append(("odds_snapshots: BEX->10bet unique-conflict rows LEFT AS-IS", n))

            overlap_where = """
              AND os.liquidity IS NULL
              AND os.captured_at >= :win AND os.captured_at <= :cutover
              AND os.market NOT IN (SELECT market FROM _op_vocab)
              AND EXISTS (
                  SELECT 1 FROM odds_snapshots s
                  WHERE s.event_id = os.event_id AND s.bookmaker = 'Betfair Sportsbook'
                    AND s.captured_at::date = os.captured_at::date
              )
            """
            n = await _exec_count(
                conn,
                _snapshot_relabel_sql(
                    extra_where=overlap_where, reason="book_mislabel_oe_recycle_overlap"
                ),
                {
                    **base,
                    "old_label": "Betfair Exchange",
                    "new_label": "10bet",
                    "reason": "book_mislabel_oe_recycle_overlap",
                },
            )
            counts.append(("odds_snapshots: BEX->'10bet' (overlap, sibling-evidenced)", n))

            ambiguous_sql = f"""
            INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason, details)
            SELECT 'odds_snapshots', os.id, 'bookmaker', 'Betfair Exchange', '10bet',
                   'ambiguous_overlap_not_restated', jsonb_build_object('applied', false)
            FROM odds_snapshots os
            WHERE os.bookmaker = 'Betfair Exchange' AND os.liquidity IS NULL
              AND os.captured_at >= :win AND os.captured_at <= :cutover
              AND os.market NOT IN (SELECT market FROM _op_vocab)
              AND NOT EXISTS (
                  SELECT 1 FROM odds_snapshots s
                  WHERE s.event_id = os.event_id AND s.bookmaker = 'Betfair Sportsbook'
                    AND s.captured_at::date = os.captured_at::date
              )
            """  # noqa: S608
            n = await _exec_count(conn, ambiguous_sql, base)
            counts.append(("odds_snapshots: overlap BEX rows AMBIGUOUS (logged, not restated)", n))

            # --- class 2: bare 'Betfair' (code BF) -> 'Betfair Exchange'
            bare_where = "AND os.captured_at >= :win AND os.captured_at < :fix"
            n = await _exec_count(
                conn,
                _snapshot_relabel_sql(extra_where=bare_where, reason="book_mislabel_bf_bare"),
                {
                    **base,
                    "old_label": "Betfair",
                    "new_label": "Betfair Exchange",
                    "reason": "book_mislabel_bf_bare",
                },
            )
            counts.append(("odds_snapshots: 'Betfair'->'Betfair Exchange'", n))

            # --- class 1: 'Betfair Sportsbook' (code BF) -> 'Betfair Exchange'
            bsb_where = "AND os.captured_at < :fix"
            n = await _exec_count(
                conn,
                _snapshot_relabel_sql(extra_where=bsb_where, reason="book_mislabel_bf_recycle"),
                {
                    **base,
                    "old_label": "Betfair Sportsbook",
                    "new_label": "Betfair Exchange",
                    "reason": "book_mislabel_bf_recycle",
                },
            )
            counts.append(("odds_snapshots: 'Betfair Sportsbook'->'Betfair Exchange'", n))
            n = await _exec_count(
                conn,
                _snapshot_conflict_log_sql(extra_where=bsb_where),
                {
                    **base,
                    "old_label": "Betfair Sportsbook",
                    "new_label": "Betfair Exchange",
                    "reason": "book_mislabel_conflict_not_restated",
                },
            )
            counts.append(("odds_snapshots: BSB->BEX unique-conflict rows LEFT AS-IS", n))

            # --- picks label columns (created_at-scoped) --------------------
            for col, old, new, lo_key in _PICK_LABEL_MAPPINGS:
                sql = f"""
                WITH upd AS (
                    UPDATE picks SET {col} = :new_label
                    WHERE {col} = :old_label
                      AND created_at >= :lo AND created_at < :fix
                    RETURNING id
                )
                INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason)
                SELECT 'picks', id, '{col}',
                       CAST(:old_label AS varchar), CAST(:new_label AS varchar),
                       'book_mislabel'
                FROM upd
                """  # noqa: S608
                n = await _exec_count(
                    conn,
                    sql,
                    {
                        "old_label": old,
                        "new_label": new,
                        "lo": base[lo_key],
                        "fix": fix_deployed_at,
                    },
                )
                counts.append((f"picks.{col}: '{old}'->'{new}'", n))

            # --- candidate_evaluations (evaluated_at-scoped) ----------------
            for col, old, new, lo_key in _CE_LABEL_MAPPINGS:
                sql = f"""
                WITH upd AS (
                    UPDATE candidate_evaluations SET {col} = :new_label
                    WHERE {col} = :old_label
                      AND evaluated_at >= :lo AND evaluated_at < :fix
                    RETURNING id
                )
                INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason)
                SELECT 'candidate_evaluations', id, '{col}',
                       CAST(:old_label AS varchar), CAST(:new_label AS varchar),
                       'book_mislabel'
                FROM upd
                """  # noqa: S608
                n = await _exec_count(
                    conn,
                    sql,
                    {
                        "old_label": old,
                        "new_label": new,
                        "lo": base[lo_key],
                        "fix": fix_deployed_at,
                    },
                )
                counts.append((f"candidate_evaluations.{col}: '{old}'->'{new}'", n))

            # --- manual_bet_logs (created_at-scoped) ------------------------
            for col, old, new, lo_key in _MBL_LABEL_MAPPINGS:
                sql = f"""
                WITH upd AS (
                    UPDATE manual_bet_logs SET {col} = :new_label
                    WHERE {col} = :old_label
                      AND created_at >= :lo AND created_at < :fix
                    RETURNING id
                )
                INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason)
                SELECT 'manual_bet_logs', id, '{col}',
                       CAST(:old_label AS varchar), CAST(:new_label AS varchar),
                       'book_mislabel'
                FROM upd
                """  # noqa: S608
                n = await _exec_count(
                    conn,
                    sql,
                    {
                        "old_label": old,
                        "new_label": new,
                        "lo": base[lo_key],
                        "fix": fix_deployed_at,
                    },
                )
                counts.append((f"manual_bet_logs.{col}: '{old}'->'{new}'", n))

            # --- trusted-CLV contamination: wrong_game-precedent re-null ----
            # Closes anchored on the mislabeled 'Betfair Exchange' (really
            # 10bet, phantom exchange-commission netting). Old values are
            # preserved in details; state shape mirrors picks 1585/2307/...
            renull_sql = f"""
            WITH sel AS (
                SELECT id, jsonb_build_object(
                    'closing_odds', closing_odds,
                    'closing_fair_probability', closing_fair_probability,
                    'clv_log', clv_log,
                    'beat_close', beat_close,
                    'closing_anchor_type', closing_anchor_type,
                    'close_anchor_book', close_anchor_book,
                    'close_snapshot_captured_at', close_snapshot_captured_at,
                    'has_snapshot_close', has_snapshot_close,
                    'close_independent_of_fill', close_independent_of_fill,
                    'prior_close_exclusion_reason', close_exclusion_reason
                ) AS d
                FROM picks
                WHERE close_anchor_book = 'Betfair Exchange'
                  AND close_snapshot_captured_at >= :cutover
                  AND close_snapshot_captured_at < :fix
                FOR UPDATE
            ), upd AS (
                UPDATE picks p SET
                    closing_odds = NULL,
                    closing_fair_probability = NULL,
                    clv_log = NULL,
                    beat_close = NULL,
                    closing_anchor_type = NULL,
                    close_anchor_book = NULL,
                    close_snapshot_captured_at = NULL,
                    has_snapshot_close = NULL,
                    close_independent_of_fill = NULL,
                    close_exclusion_reason = 'book_mislabel'
                FROM sel WHERE p.id = sel.id
                RETURNING p.id
            )
            INSERT INTO {AUDIT_TABLE} (table_name, row_id, column_name,
        old_label, new_label, reason, details)
            SELECT 'picks', sel.id, 'close_anchor_book', 'Betfair Exchange', NULL,
                   'book_mislabel_close_renull', sel.d
            FROM sel JOIN upd ON upd.id = sel.id
            """  # noqa: S608
            n = await _exec_count(conn, renull_sql, base)
            counts.append(("picks: close re-null (close_exclusion_reason='book_mislabel')", n))

            # --- report -----------------------------------------------------
            mode = "APPLY" if apply else "DRY-RUN (rolled back)"
            print(f"\n=== bookmaker label restatement — {mode} ===")
            print(f"window: [{WINDOW_START.isoformat()}, {fix_deployed_at.isoformat()})")
            print(f"oddsportal cutover: {ODDSPORTAL_CUTOVER.isoformat()}\n")
            width = max(len(label) for label, _ in counts)
            for label, count in counts:
                print(f"  {label:<{width}}  {count:>9}")
            total = sum(
                c for label, c in counts if "LEFT AS-IS" not in label and "AMBIGUOUS" not in label
            )
            print(f"\n  total rows restated/re-nulled: {total}")

            if apply:
                await trans.commit()
                print("\nCOMMITTED. Audit rows in bookmaker_label_restatements.")
            else:
                await trans.rollback()
                print("\nROLLED BACK (dry run). Re-run with --apply to execute.")
    finally:
        await engine.dispose()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute for real (default is dry-run: run everything, print counts, roll back).",
    )
    parser.add_argument(
        "--fix-deployed-at",
        type=datetime.fromisoformat,
        default=DEFAULT_FIX_DEPLOYED_AT,
        help="UTC ISO-8601 stamp when the c611bc5 fix went live "
        f"(default {DEFAULT_FIX_DEPLOYED_AT.isoformat()}).",
    )
    args = parser.parse_args()
    if args.fix_deployed_at.tzinfo is None:
        parser.error("--fix-deployed-at must be timezone-aware (append +00:00)")
    return args


if __name__ == "__main__":
    ns = _parse_args()
    asyncio.run(run(apply=ns.apply, fix_deployed_at=ns.fix_deployed_at))
