"""Restate tennis GAME-handicap spreads wrongly graded from SET scores.

Background (settlement audit 2026-08-02, operator-approved restatement):
post-2026-07-11 mint vocabulary namespaces tennis SET handicaps as
``spreads_sets_*`` (OddsPortal set-AH keys carry a ``_sets`` suffix), while
GAME handicaps keep the plain ``spreads_minus_*``/``spreads_plus_*`` details
(or predate the namespace: NULL detail). The settlement guard
(``is_tennis_game_line``) gated on |line| > 2.5 magnitude ONLY, so game
handicaps quoted at -0.5/-1.5/-2.5 passed and ``_settle_spreads`` graded them
against 2-0/2-1 SET scores. Evidence: ``spreads_minus_2_5`` 0W/102L
(impossible — the max best-of-3 set margin is 2; p ~ 1e-24 at fair ~0.42);
``spreads_minus_1_5`` 41W/102L at fair 0.464; ~356 defective grades; family
P&L -2,588.21 (-64% ROI).

Target family = tennis picks, market='spreads', whose ``market_detail`` does
NOT prove the SETS axis (NOT LIKE 'spreads_sets%', not an
'asian_handicap%_sets' key, or NULL), settled won/lost/half_won/half_lost via
a SET-score source (result_tracking.home_score + away_score <= 5 — the stored
score IS the score that graded the pick). Push/void grades and picks not in
status 'settled' are left untouched (counted + reported).

Action (wrong_game re-null precedent): return the picks to the UNSETTLED
state — the ``result_tracking`` row is DELETED (its ``outcome`` column is NOT
NULL, so "re-null to unsettled" means removing the row; the
``uq_result_tracking_pick`` constraint then admits a fresh, honest row later)
and ``picks.status`` flips 'settled' -> 'alerted', the exact pre-settlement
state the engine re-examines. Every removed/changed value is preserved in the
``settlement_restatements`` audit table (pick_id, column_name, old_value,
new_value, reason='set_score_axis_mislabel', restated_at) — one row per
column, mirroring ``bookmaker_label_restatements`` conventions. This script
deliberately does NOT re-grade: a games-level re-grade from tennis_data.co.uk
is a follow-up that will read this audit table.

INTERLOCK (verified by tests/test_restate_tennis_spread_grades.py): this
script MUST run only with the axis-aware settlement guard deployed
(app/settlement/outcomes.py::tennis_set_score_ungradeable requiring a
sets-axis ``market_detail``). With that guard live, the next settlement cycle
CANNOT re-grade a re-nulled pick from a set score — the candidate loop and
``_settle_one`` both refuse (non-sets/NULL detail) and leave it 'alerted' for
manual/games-level entry. The scraped-finals tennis exclusion and the ESPN
completion classifier close the remaining set-score sources. The bounded
no-result expiry policies may EVENTUALLY void a re-nulled pick whose result
sources have gone dark (note='expired_no_result_source') — an auditable,
restatable stake-returned terminal state, never a wrong grade.

Usage (dry-run is the DEFAULT — executes everything in one transaction and
ROLLS BACK, printing exact counts):

    uv run python scripts/restate_tennis_spread_grades.py
    uv run python scripts/restate_tennis_spread_grades.py --apply

Run with the scheduler stopped. Decision-support data hygiene only — this
script never touches betting execution (none exists).
"""

from __future__ import annotations

import argparse
import asyncio
from typing import Final

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

RESTATEMENT_REASON: Final[str] = "set_score_axis_mislabel"
AUDIT_TABLE: Final[str] = "settlement_restatements"

_CREATE_AUDIT: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {AUDIT_TABLE} (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_id      BIGINT       NOT NULL,
    column_name  VARCHAR(64)  NOT NULL,
    old_value    TEXT,
    new_value    TEXT,
    reason       VARCHAR(128) NOT NULL,
    restated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
)
"""

# The defective family, materialized once per run so selection, audit, delete
# and status flip all act on the IDENTICAL row set. Sets-axis details
# ('spreads_sets%', 'asian_handicap%_sets' — outcomes.is_tennis_sets_spread
# _detail) are excluded: those grades are legitimate. LIKE '\_' escapes keep
# the underscore literal (Postgres default escape).
_CREATE_SELECTION: Final[str] = r"""
CREATE TEMP TABLE _tsr_sel ON COMMIT DROP AS
SELECT rt.id AS rt_id, rt.pick_id, rt.outcome, rt.pnl, rt.roi,
       rt.settled_stake_amount, rt.settled_effective_odds,
       rt.home_score, rt.away_score, rt.note, rt.settled_at,
       p.market_detail, p.status
FROM result_tracking rt
JOIN picks p  ON p.id = rt.pick_id
JOIN events e ON e.id = p.event_id
JOIN sports s ON s.id = e.sport_id
WHERE s.key = 'tennis'
  AND p.market = 'spreads'
  AND (
        p.market_detail IS NULL
        OR (
             lower(p.market_detail) NOT LIKE 'spreads\_sets%'
             AND NOT (
                 lower(p.market_detail) LIKE 'asian\_handicap%'
                 AND lower(p.market_detail) LIKE '%\_sets'
             )
           )
      )
  AND rt.outcome IN ('won', 'lost', 'half_won', 'half_lost')
  AND rt.home_score IS NOT NULL
  AND rt.away_score IS NOT NULL
  AND rt.home_score + rt.away_score <= 5
"""

# Rows in the family whose pick is NOT restatable (status moved on — e.g.
# 'superseded'); reported, never touched.
_COUNT_NON_SETTLED: Final[str] = "SELECT count(*) FROM _tsr_sel WHERE status <> 'settled'"

_LOCK_ROWS: Final[str] = """
SELECT p.id FROM picks p
WHERE p.id IN (SELECT pick_id FROM _tsr_sel WHERE status = 'settled')
FOR UPDATE
"""

# One audit row per re-nulled column (old value preserved as text; new_value
# NULL = column gone with the deleted result row, 'alerted' for the status).
_INSERT_AUDIT: Final[str] = f"""
INSERT INTO {AUDIT_TABLE} (pick_id, column_name, old_value, new_value, reason)
SELECT sel.pick_id,
       v.column_name,
       v.old_value,
       CASE WHEN v.column_name = 'picks.status' THEN 'alerted' END,
       :reason
FROM _tsr_sel sel
CROSS JOIN LATERAL (VALUES
    ('result_tracking.outcome',                sel.outcome::text),
    ('result_tracking.pnl',                    sel.pnl::text),
    ('result_tracking.roi',                    sel.roi::text),
    ('result_tracking.settled_stake_amount',   sel.settled_stake_amount::text),
    ('result_tracking.settled_effective_odds', sel.settled_effective_odds::text),
    ('result_tracking.home_score',             sel.home_score::text),
    ('result_tracking.away_score',             sel.away_score::text),
    ('result_tracking.note',                   sel.note::text),
    ('result_tracking.settled_at',             sel.settled_at::text),
    ('picks.status',                           sel.status)
) AS v(column_name, old_value)
WHERE sel.status = 'settled'
"""  # noqa: S608 - table name is an internal literal

_DELETE_RESULTS: Final[str] = """
DELETE FROM result_tracking
WHERE id IN (SELECT rt_id FROM _tsr_sel WHERE status = 'settled')
"""

_REOPEN_PICKS: Final[str] = """
UPDATE picks SET status = 'alerted'
WHERE id IN (SELECT pick_id FROM _tsr_sel WHERE status = 'settled')
  AND status = 'settled'
"""

_BREAKDOWN: Final[str] = """
SELECT coalesce(market_detail, '<NULL>') AS family,
       count(*) AS n,
       count(*) FILTER (WHERE outcome IN ('won', 'half_won')) AS wins
FROM _tsr_sel
WHERE status = 'settled'
GROUP BY 1
ORDER BY n DESC
"""


async def restate(
    conn: AsyncConnection,
) -> tuple[list[tuple[str, int]], list[tuple[str, int, int]]]:
    """Execute the restatement on an ALREADY-BEGUN transaction (caller owns
    commit/rollback — the CLI wrapper below and the test suite both drive
    this). Returns (counts, per-family breakdown [(family, n, wins)])."""
    counts: list[tuple[str, int]] = []
    await conn.execute(text(_CREATE_AUDIT))
    await conn.execute(text(_CREATE_SELECTION))
    total = int(await conn.scalar(text("SELECT count(*) FROM _tsr_sel")) or 0)
    null_detail = int(
        await conn.scalar(text("SELECT count(*) FROM _tsr_sel WHERE market_detail IS NULL")) or 0
    )
    non_settled = int(await conn.scalar(text(_COUNT_NON_SETTLED)) or 0)
    breakdown = [
        (str(family), int(n), int(wins))
        for family, n, wins in (await conn.execute(text(_BREAKDOWN))).all()
    ]
    counts.append(("family rows matched (defective set-score spread grades)", total))
    counts.append(("  of which NULL market_detail", null_detail))
    counts.append(("  of which pick no longer 'settled' (reported, untouched)", non_settled))
    await conn.execute(text(_LOCK_ROWS))
    audit_rows = (await conn.execute(text(_INSERT_AUDIT), {"reason": RESTATEMENT_REASON})).rowcount
    counts.append((f"{AUDIT_TABLE} audit rows written (one per column)", int(audit_rows or 0)))
    deleted = (await conn.execute(text(_DELETE_RESULTS))).rowcount
    counts.append(("result_tracking rows re-nulled (deleted)", int(deleted or 0)))
    reopened = (await conn.execute(text(_REOPEN_PICKS))).rowcount
    counts.append(("picks re-opened: status 'settled' -> 'alerted'", int(reopened or 0)))
    return counts, breakdown


async def run(*, apply: bool) -> None:
    from app.config import get_settings
    from app.database import create_engine

    engine = create_engine(get_settings())
    try:
        async with engine.connect() as conn:
            trans = await conn.begin()
            counts, breakdown = await restate(conn)
            mode = "APPLY" if apply else "DRY-RUN (rolled back)"
            print(f"\n=== tennis set-score spread-grade restatement — {mode} ===")
            print(f"reason: {RESTATEMENT_REASON}\n")
            width = max(len(label) for label, _ in counts)
            for label, count in counts:
                print(f"  {label:<{width}}  {count:>7}")
            print("\n  per-family breakdown (settled family rows):")
            for family, n, wins in breakdown:
                print(f"    {family:<32}  n={n:<5} wins={wins}")
            if apply:
                await trans.commit()
                print(f"\nCOMMITTED. Audit rows in {AUDIT_TABLE}.")
                print(
                    "Interlock: the axis-aware settlement guard must already be "
                    "deployed — re-opened picks defer (never re-grade) from set scores."
                )
            else:
                await trans.rollback()
                print("\nROLLED BACK (dry run). Re-run with --apply to execute.")
    finally:
        await engine.dispose()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute for real (default is dry-run: run everything, print counts, roll back).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(run(apply=_parse_args().apply))
