"""Withdraw 5 audited artifact picks to the terminal 'superseded' state.

Background (audit 2026-08-02, Defect 2, operator-approved withdrawal): five
picks were minted from pre-fix product-mix devig groups or from >24h-stale
fill quotes — they are artifacts of defective mint inputs, not genuine +EV
detections, and must never settle into pnl/ROI/CLV. Per-pick defect class:

    946692, 946693, 946584 -> 'product_mismatch_artifact'
    952527, 952702         -> 'stale_quote_artifact'

Action: transition each pick from 'alerted' to the codebase's EXISTING
terminal non-bet state ``status='superseded'`` — the same bare status flip
every live supersede path performs (repositories.py::_supersede_older_versions
~5030, settlement engine dedup guards engine.py ~259/~827/~1119, manual-path
parking routes.py ~1799). No supersede path clears any other column, so this
script deliberately does not either. A superseded pick writes NO
result_tracking row, is excluded from settlement (only 'alerted' rows are
candidates), from CLV revalidation/true-up ('alerted'-scoped), from the
provisional display grade (repositories.py ~873), from exposure counters, and
manual settlement 409s it (routes.py ~1736). Rows are never deleted.

Safety rails: only rows still 'alerted' AND without a result_tracking row are
touched; anything already terminal/settled is reported and left alone (a
settled artifact needs a re-null restatement instead — out of scope here).
Every change lands in the ``pick_withdrawals`` audit table (pick_id,
column_name, old_value, new_value, reason, withdrawn_at) — one row per
changed column, mirroring ``settlement_restatements`` conventions — fully
reversible.

Usage (dry-run is the DEFAULT — executes everything in one transaction and
ROLLS BACK, printing the exact per-pick changes):

    uv run python scripts/withdraw_artifact_picks.py
    uv run python scripts/withdraw_artifact_picks.py --apply

Decision-support data hygiene only — this script never touches betting
execution (none exists).
"""

from __future__ import annotations

import argparse
import asyncio
from typing import Final

from sqlalchemy import bindparam, text
from sqlalchemy.ext.asyncio import AsyncConnection

#: The operator-audited withdrawal set: pick id -> defect-class reason.
WITHDRAWAL_REASONS: Final[dict[int, str]] = {
    946584: "product_mismatch_artifact",
    946692: "product_mismatch_artifact",
    946693: "product_mismatch_artifact",
    952527: "stale_quote_artifact",
    952702: "stale_quote_artifact",
}

#: The codebase's canonical terminal non-bet status (see module docstring).
TERMINAL_STATUS: Final[str] = "superseded"

AUDIT_TABLE: Final[str] = "pick_withdrawals"

_CREATE_AUDIT: Final[str] = f"""
CREATE TABLE IF NOT EXISTS {AUDIT_TABLE} (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_id      BIGINT       NOT NULL,
    column_name  VARCHAR(64)  NOT NULL,
    old_value    TEXT,
    new_value    TEXT,
    reason       VARCHAR(128) NOT NULL,
    withdrawn_at TIMESTAMPTZ  NOT NULL DEFAULT now()
)
"""

# The audited rows, locked for this transaction, with settled-ness evidence
# (a result_tracking row means money already landed — never touched here).
_SELECT_TARGETS: Final[str] = """
SELECT p.id, p.status, p.tier, p.market, p.market_detail, p.selection,
       p.bookmaker, p.decimal_odds, p.recommended_stake_amount,
       rt.id AS rt_id, rt.outcome AS rt_outcome
FROM picks p
LEFT JOIN result_tracking rt ON rt.pick_id = p.id
WHERE p.id IN :ids
ORDER BY p.id
FOR UPDATE OF p
"""

_INSERT_AUDIT: Final[str] = f"""
INSERT INTO {AUDIT_TABLE} (pick_id, column_name, old_value, new_value, reason)
VALUES (:pick_id, 'picks.status', :old_value, :new_value, :reason)
"""  # noqa: S608 - table name is an internal literal

# Bare status flip — the exact transition every live supersede path performs.
# The status predicate makes an accidental second --apply a no-op.
_WITHDRAW: Final[str] = """
UPDATE picks SET status = :new_status
WHERE id = :pick_id AND status = 'alerted'
"""


async def withdraw(conn: AsyncConnection) -> tuple[list[str], int]:
    """Execute the withdrawal on an ALREADY-BEGUN transaction (caller owns
    commit/rollback — the CLI wrapper below and the test suite both drive
    this). Returns (per-pick report lines, number of picks withdrawn)."""
    lines: list[str] = []
    withdrawn = 0
    await conn.execute(text(_CREATE_AUDIT))
    rows = (
        await conn.execute(
            text(_SELECT_TARGETS).bindparams(bindparam("ids", expanding=True)),
            {"ids": sorted(WITHDRAWAL_REASONS)},
        )
    ).all()
    found_ids = {int(row.id) for row in rows}
    for missing in sorted(set(WITHDRAWAL_REASONS) - found_ids):
        lines.append(f"pick {missing}: NOT FOUND — skipped")
    for row in rows:
        pick_id = int(row.id)
        reason = WITHDRAWAL_REASONS[pick_id]
        label = (
            f"pick {pick_id} [{row.tier}] {row.market}/{row.market_detail} "
            f"'{row.selection}' @ {row.decimal_odds} ({row.bookmaker}) "
            f"stake {row.recommended_stake_amount}"
        )
        if row.rt_id is not None:
            lines.append(
                f"{label}: SETTLED (result_tracking id={row.rt_id}, "
                f"outcome={row.rt_outcome}) — refused, needs a re-null "
                "restatement instead"
            )
            continue
        if row.status != "alerted":
            lines.append(f"{label}: status '{row.status}' already terminal — skipped")
            continue
        updated = (
            await conn.execute(text(_WITHDRAW), {"new_status": TERMINAL_STATUS, "pick_id": pick_id})
        ).rowcount
        if not updated:  # pragma: no cover - row locked above; defensive only
            lines.append(f"{label}: concurrent status change — skipped")
            continue
        await conn.execute(
            text(_INSERT_AUDIT),
            {
                "pick_id": pick_id,
                "old_value": row.status,
                "new_value": TERMINAL_STATUS,
                "reason": reason,
            },
        )
        lines.append(f"{label}: status 'alerted' -> '{TERMINAL_STATUS}' reason={reason}")
        withdrawn += 1
    return lines, withdrawn


async def run(*, apply: bool) -> None:
    from app.config import get_settings
    from app.database import create_engine

    engine = create_engine(get_settings())
    try:
        async with engine.connect() as conn:
            trans = await conn.begin()
            lines, withdrawn = await withdraw(conn)
            mode = "APPLY" if apply else "DRY-RUN (rolled back)"
            print(f"\n=== artifact-pick withdrawal — {mode} ===")
            print(f"terminal status: '{TERMINAL_STATUS}' (audit table: {AUDIT_TABLE})\n")
            for line in lines:
                print(f"  {line}")
            print(f"\n  picks withdrawn: {withdrawn} of {len(WITHDRAWAL_REASONS)} audited")
            if apply:
                await trans.commit()
                print(f"\nCOMMITTED. Audit rows in {AUDIT_TABLE}.")
            else:
                await trans.rollback()
                print("\nROLLED BACK (dry run). Re-run with --apply to execute.")
    finally:
        await engine.dispose()


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Execute for real (default is dry-run: run everything, print changes, roll back).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    asyncio.run(run(apply=_parse_args().apply))
